version: '3'

networks:
  default:
    external:
      name: maze-network

services:
  maze-client:
    container_name: maze-client
    build: .
    env_file: local.env
    ports:
      # Webserver
      - 8080:8080
      # HMR Websocket
      - 8081:8081
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
